### ISSUE TITLE
답변보기와 답변없음 버튼 구분

### ISSUE THREAD

**Issue by gem1n1-youngjae** [themoment-team/the_moment_front#134]
![image](https://user-images.githubusercontent.com/57673815/121485743-774e4000-ca0b-11eb-9001-1c381cf0db80.png)
답변보기와 답변없음 버튼의 스타일이 동일하여
어떤 의견이 답변이 남겨졌는지 알기가 쉽지 않습니다.
둘이 스타일을 따로 지정하는게 구분이 쉬울듯 합니다.

**Comment by Goolgae** [comment]
하이라이팅을 말씀하시는거죠?

**Comment by pdlma0904** [comment]
아니요 focus나 hover같은 이벤트가 발생하기 전에 구분되는것을 바라고 있습니다.

**Comment by iseolin76** [comment]
처음 버튼 디자인 자체가 색 등으로 구별되는 걸 말씀하시는거죠?

**Comment by pdlma0904** [comment]
넵 맞습니다. 하이라이팅도 UX적으로 좋은 방법이라고 생각합니다.

**Comment by sunwoo0706** [comment]
#217
