### ISSUE TITLE
반응형 오류

### ISSUE THREAD

**Issue by KimGiHong** [themoment-team/the_moment_front#153]
<img width="1250" alt="스크린샷 2021-07-06 오전 11 17 13" src="https://user-images.githubusercontent.com/68697807/124532780-21bf5480-de4c-11eb-91dd-fa0c6f9da4dc.png">
의도한 것인지 아닌지 모르겠지만 페이지를 줄였을때 반응형 문제가 있는 것으로 보입니다.

**Comment by sunwoo0706** [comment]
딱 그 px 에서만 해당이 되는 모양입니다. 혹시 시간이 되신다면 해당 px을 적어주세요 !!

**Comment by KimGiHong** [comment]
1297px부터 해당되네요

**Comment by sunwoo0706** [comment]
1201px까지 해당하는군요

**Comment by sunwoo0706** [comment]
테스트
