### ISSUE TITLE
github link

### ISSUE THREAD

**Issue by baekteun** [themoment-team/the_moment_front#222]
## the-moment에서 이런 문제가 발생했어요!
> 깃허브 링크 이상해요
<img width="587" alt="스크린샷 2021-11-03 오후 3 01 07" src="https://user-images.githubusercontent.com/74440939/140015719-25883721-d223-4fe6-9732-e726a94a35f7.png">
<img width="631" alt="스크린샷 2021-11-03 오후 3 02 15" src="https://user-images.githubusercontent.com/74440939/140015779-3021342f-060e-4eb7-9a58-fa6136df3955.png">

**Comment by sunwoo0706** [comment]
이슈 감사합니다 빨리 픽스하도록 하겠습니다

**Comment by sunwoo0706** [comment]
현재 `origin:develop` 기준 이미 픽스 되어있었습니다.
